// seed-duplicate.ts — fixture seed file with KNOWN duplication.
// forge:simplify is expected to remove the duplicated functions below.
// Do NOT edit this file by hand — it is the known-bad input for the simplify fixture.

// DUPLICATE 1: two functions that do exactly the same thing (format a name)
function formatFullName(first: string, last: string): string {
  return `${first} ${last}`.trim();
}

function buildFullName(first: string, last: string): string {
  return `${first} ${last}`.trim();
}

// DUPLICATE 2: two functions that both clamp a number to [0, 100]
function clampToHundred(n: number): number {
  if (n < 0) return 0;
  if (n > 100) return 100;
  return n;
}

function normalizeToHundred(n: number): number {
  if (n < 0) return 0;
  if (n > 100) return 100;
  return n;
}

// Usage — both pairs are called so a naive dead-code pass cannot just delete one
export function renderLabel(first: string, last: string, score: number): string {
  const name1 = formatFullName(first, last);
  const name2 = buildFullName(first, last);
  const clamped1 = clampToHundred(score);
  const clamped2 = normalizeToHundred(score);
  return `${name1}/${name2} — ${clamped1}/${clamped2}`;
}
