#!/usr/bin/env python3
"""Generate INDEX.md from frontmatter of plugins/forge/{skills,agents}/*.md"""

import re
import sys
from datetime import date
from pathlib import Path
from collections import defaultdict

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*", re.DOTALL)


def parse_frontmatter(text: str) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    block = m.group(1)
    out = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if ":" in line and not line.startswith(" ") and not line.startswith("\t"):
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip()

            # Handle YAML block scalars: > (folded) or | (literal)
            if v in (">", "|"):
                scalar_lines = []
                i += 1
                while i < len(lines) and (lines[i].startswith(" ") or lines[i].startswith("\t")):
                    scalar_lines.append(lines[i].strip())
                    i += 1
                # Folded (>) joins with spaces; literal (|) joins with newlines
                if v == ">":
                    out[k] = " ".join(scalar_lines)
                else:
                    out[k] = "\n".join(scalar_lines)
                continue
            else:
                # Strip surrounding quotes if present
                if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                    v = v[1:-1]
                out[k] = v
        i += 1
    return out


def collect(dir_path: Path) -> list:
    items = []
    if not dir_path.exists():
        return items
    for md in sorted(dir_path.glob("*.md")):
        # skip README / index / docs by name
        if md.name.lower() in {"readme.md", "index.md"}:
            continue
        fm = parse_frontmatter(md.read_text())
        if not fm.get("name"):
            # fallback to filename
            fm["name"] = md.stem
        items.append({
            "name": fm.get("name", md.stem),
            "description": fm.get("description", "").strip() or "(no description)",
            "category": fm.get("category", "uncategorized").strip(),
            "path": str(md),
        })
    return items


def render_section(heading: str, items_by_cat: dict, prefix: str = "") -> str:
    out = [f"## {heading}\n"]
    # alphabetize categories, but put 'uncategorized' last
    cats = sorted(items_by_cat.keys(), key=lambda c: (c == "uncategorized", c))
    for cat in cats:
        out.append(f"### {cat}\n")
        for it in sorted(items_by_cat[cat], key=lambda i: i["name"]):
            out.append(f"- `{prefix}{it['name']}` — {it['description']}")
        out.append("")
    return "\n".join(out)


def main(commands_dir: str, agents_dir: str) -> int:
    cmd_items = collect(Path(commands_dir))
    agent_items = collect(Path(agents_dir))

    cmd_by_cat = defaultdict(list)
    for it in cmd_items:
        cmd_by_cat[it["category"]].append(it)
    agent_by_cat = defaultdict(list)
    for it in agent_items:
        agent_by_cat[it["category"]].append(it)

    today = date.today().isoformat()
    sys.stdout.write(f"# Skills & Agents Index (auto-generated)\n\nLast regenerated: {today}\n\n")
    sys.stdout.write("> This file is generated by `plugins/forge/scripts/generate-index.sh`. Do not edit manually.\n")
    sys.stdout.write("> To regenerate: `plugins/forge/scripts/generate-index.sh`\n\n")

    sys.stdout.write(render_section("Skills (slash commands)", cmd_by_cat, prefix="/"))
    sys.stdout.write("\n")
    sys.stdout.write(render_section("Agents (Task subagents)", agent_by_cat, prefix=""))

    # Warnings to stderr if any uncategorized
    uncats = [it for it in cmd_items + agent_items if it["category"] == "uncategorized"]
    if uncats:
        sys.stderr.write(f"WARN: {len(uncats)} files missing category:\n")
        for it in uncats:
            sys.stderr.write(f"  - {it['path']}\n")
        return 1
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.stderr.write("Usage: _generate_index.py <commands_dir> <agents_dir>\n")
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
