#!/usr/bin/env python3
"""Generate per-project SKILLS.md filtered by stack.

Usage: _generate_project_skills.py <stack>
Stack values: web-react | mobile-flutter | mobile-native | backend-node | library | agnostic
"""

import re
import sys
from datetime import date
from pathlib import Path
from collections import defaultdict

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*", re.DOTALL)


def parse_frontmatter(text: str) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    block = m.group(1)
    out = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if ":" in line and not line.startswith(" ") and not line.startswith("\t"):
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip()

            # Handle YAML block scalars: > (folded) or | (literal)
            if v in (">", "|"):
                scalar_lines = []
                i += 1
                while i < len(lines) and (lines[i].startswith(" ") or lines[i].startswith("\t")):
                    scalar_lines.append(lines[i].strip())
                    i += 1
                # Folded (>) joins with spaces; literal (|) joins with newlines
                if v == ">":
                    out[k] = " ".join(scalar_lines)
                else:
                    out[k] = "\n".join(scalar_lines)
                continue
            else:
                # Strip surrounding quotes if present
                if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                    v = v[1:-1]
                out[k] = v
        i += 1
    return out


def parse_stacks(value: str) -> list:
    """Parse `stacks: [a, b]` or `stacks: a` into a list."""
    if not value:
        return []
    v = value.strip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        if not inner:
            return []
        return [x.strip().strip("'\"") for x in inner.split(",")]
    return [v.strip("'\"")]


def collect(dir_path, stack_filter):
    items = []
    if not dir_path.exists():
        return items
    for md in sorted(dir_path.glob("*.md")):
        if md.name.lower() in {"readme.md", "index.md"}:
            continue
        fm = parse_frontmatter(md.read_text())
        stacks = parse_stacks(fm.get("stacks", ""))
        # Include if stacks absent (agnostic) OR contains the requested stack
        if stacks and stack_filter not in stacks:
            continue
        items.append({
            "name": fm.get("name", md.stem),
            "description": fm.get("description", "").strip() or "(no description)",
            "category": fm.get("category", "uncategorized").strip(),
            "stacks": stacks,
        })
    return items


def main(stack):
    home = Path.home() / ".claude"
    cmd_items = collect(home / "commands", stack)
    agent_items = collect(home / "agents", stack)

    cmd_by_cat = defaultdict(list)
    for it in cmd_items:
        cmd_by_cat[it["category"]].append(it)
    agent_by_cat = defaultdict(list)
    for it in agent_items:
        agent_by_cat[it["category"]].append(it)

    today = date.today().isoformat()
    out = sys.stdout
    out.write(f"# Skills for this project\n\n")
    out.write(f"Stack: `{stack}`  \nGenerated: {today}\n\n")
    out.write("> This file is auto-generated by `/project-init`.\n")
    out.write("> Lists global skills (from `plugins/forge/skills/` and `plugins/forge/agents/`) filtered for this stack.\n")
    out.write("> Project-local skills in `<project>/.claude/skills/` are not listed here — see that folder for kit-* skills.\n\n")

    out.write("## Skills (slash commands)\n\n")
    for cat in sorted(cmd_by_cat.keys()):
        out.write(f"### {cat}\n\n")
        for it in sorted(cmd_by_cat[cat], key=lambda i: i["name"]):
            stack_marker = ""
            if it["stacks"]:
                stack_marker = f" _(stack: {', '.join(it['stacks'])})_"
            out.write(f"- `/{it['name']}` — {it['description']}{stack_marker}\n")
        out.write("\n")

    out.write("## Agents (Task subagents)\n\n")
    for cat in sorted(agent_by_cat.keys()):
        out.write(f"### {cat}\n\n")
        for it in sorted(agent_by_cat[cat], key=lambda i: i["name"]):
            stack_marker = ""
            if it["stacks"]:
                stack_marker = f" _(stack: {', '.join(it['stacks'])})_"
            out.write(f"- `{it['name']}` — {it['description']}{stack_marker}\n")
        out.write("\n")

    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write("Usage: _generate_project_skills.py <stack>\n")
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
